version: '1'
networks:
  web-network:

services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:3.5.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - web-network

  etcdKeeper:
    hostname: etcdKeeper
    image: evildecay/etcdkeeper:v0.7.6
    ports:
      - "8099:8080"
    networks:
      - web-network
  mysql:
    hostname: mysql
    image: mysql:latest
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=dy
      - MYSQL_USER=dy
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"'
