version: '1'
networks:
  web-network:

services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:3.5.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - web-network

  etcdkeeper:
    hostname: etcdkeeper
    image: evildecay/etcdkeeper:v0.7.6
    ports:
      - "8099:8080"
    networks:
      - web-network
#  TODO: 完成 mysql 的书写
#  mysql:
#    hostname: zsj
#    image: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: "az123."
#      MYSQL_USER: 'zsj'
#      MYSQL_PASS: 'az123.'
