// Code generated by Kitex v0.4.4. DO NOT EDIT.

package chatservice

import (
	"context"
	user "first/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMsg(ctx context.Context, Req *user.SaveMsgRequest, callOptions ...callopt.Option) (r *user.SaveMsgResponse, err error)
	GetChatList(ctx context.Context, Req *user.GetChatListRequest, callOptions ...callopt.Option) (r *user.GetChatListResponse, err error)
	GetFriendChatList(ctx context.Context, Req *user.GetFriendChatRequest, callOptions ...callopt.Option) (r *user.GetFriendChatResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) SendMsg(ctx context.Context, Req *user.SaveMsgRequest, callOptions ...callopt.Option) (r *user.SaveMsgResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMsg(ctx, Req)
}

func (p *kChatServiceClient) GetChatList(ctx context.Context, Req *user.GetChatListRequest, callOptions ...callopt.Option) (r *user.GetChatListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChatList(ctx, Req)
}

func (p *kChatServiceClient) GetFriendChatList(ctx context.Context, Req *user.GetFriendChatRequest, callOptions ...callopt.Option) (r *user.GetFriendChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendChatList(ctx, Req)
}
